default_flags = "-gh"
modal = true
initial_mode = "command"
show_selection_mark = true
true_colors = true
syntax_theme = "MochaDark"
content_search_max_file_size = "10MB"
enable_kitty_keyboard = false
lines_before_match_in_preview = 1
lines_after_match_in_preview = 1
icon_theme = "nerdfont"

[[imports]]
luma = ["dark", "unknown"]
# file = "skins/native-16.toml"
# file = "skins/catppuccin-mocha.toml"
file = "skins/kanagawa.toml"

[[imports]]
file = "verbs.toml"

[special-paths]
"/media" = { list = "never", sum = "never" }
"~/.config" = { show = "always" }
"trav" = { show = "always", list = "always", sum = "never" }
# "~/useless" = { show = "never" }
# "~/my-link-I-want-to-explore" = { list = "always" }

[ext-colors]
png = "rgb(255, 128, 75)"
rs = "ansi(208)"
toml = "ansi(105)"
