theme = "kanagawa"
[editor]
bufferline = "multiple"
# bufferline = "never"
cursorline = true
line-number = "absolute"
# line-number = "relative"
popup-border = "all"
auto-save = true
# rulers = [100]
# text-width = 100
true-color = true
mouse = true
scrolloff = 10
shell = ["zsh", "-c"]
color-modes = true
auto-pairs = true
idle-timeout = 50


[editor.gutters]
# layout = ["diagnostics", "spacer", "diff"]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""
# wrap-at-text-width = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "🚀 NOR"
mode.insert = "📝 INS"
mode.select = "🌟 SEL"


[editor.lsp]
display-inlay-hints = true
display-messages = true
# display-signature-help-docs = true
# auto-signature-help=true

[keys.normal]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
x = "delete_selection"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection",
]
o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
H = ":bp"
L = ":bn"
esc = ["collapse_selection", "keep_primary_selection"]
C-c = "no_op"


[keys.normal.y]
y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection",
]

[keys.normal.d]
d = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]

[keys.normal.space]
n = ":new"

# [keys.normal.space.","]
[keys.normal.';']
f = ":toggle auto-format"
i = ":toggle lsp.display-inlay-hints"
k = ":toggle file-picker.hidden"
d = ":toggle indent-guides.render"
x = ":buffer-close"
X = ":buffer-close-others"
q = ":q"
Q = ":qa!"
w = ":write"
r = [":w", ":config-reload"]
o = ":config-open"
l = ":log-open"

e = ":sh helix-wezterm.sh explorer"

y = ":yank-diagnostic"
n = ":open ~/Docs/kaidev0711/index.md"
# k = "hover"


[keys.insert]
C-space = "completion"
j = { k = "normal_mode" }
# k = { j = "normal_mode" }
esc = ["collapse_selection", "normal_mode"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
G = "goto_file_end"
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection",
]
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection",
  "normal_mode",
]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-c = "no_op"
